### PR TITLE
change config data "pci_bdf" in all LNT to "lnt_pci_bdf"

### PR DESCRIPTION
**Pull request by sjwahub**
Signed-off-by: Shujun Wang <shujun.wang@intel.com>

In corresponding to the change of test_to_run.txt, where the parameter "pci_bdf" is changed to "pci_bdf" and "lnt_pci_bdf", the config_data for pci_bdf in all LNT are changed to "lnt_pci_bdf".

The test log [TestingLog.txt](https://github.com/ipdk-io/ptf-tests/files/10362378/TestingLog.txt)

### CODE REVIEW

**Review by dkaranjai — CHANGES_REQUESTED** [review]
minor change:

the below message is getting printed in the log file, which is not needed. please remove the corresponding log.info():

12/27/2022,14:8:59  INFO: True
12/27/2022,14:8:59  INFO: ['Vm1']

**Comment by sjwahub** [comment]
> minor change:
> 
> the below message is getting printed in the log file, which is not needed. please remove the corresponding log.info():
> 
> 12/27/2022,14:8:59 INFO: True 12/27/2022,14:8:59 INFO: ['Vm1']

Done

**Comment by sjwahub** [comment]
Update:
1. All variable "pci_bdf" are replace by "lnt_pci_bdf"
2. All delete local ovs bridge code in teardown() are removed. Expecting pre-test.sh can help to clean up
3.Test Suite Run log [ptf_tests_run_lnt_all_release.log](https://github.com/ipdk-io/ptf-tests/files/10485896/ptf_tests_run_lnt_all_release.log)
4. Fix for l3_dpdk_port_flapping_with_link_ports.py.  Unit test log [l3_dpdk_port_flap_with_link_log.txt](https://github.com/ipdk-io/ptf-tests/files/10486044/l3_dpdk_port_flap_with_link_log.txt)

**Comment by dkaranjai** [comment]
> Update:
> 
> 1. All variable "pci_bdf" are replace by "lnt_pci_bdf"
> 2. All delete local ovs bridge code in teardown() are removed. Expecting pre-test.sh can help to clean up
>    3.Test Suite Run log [ptf_tests_run_lnt_all_release.log](https://github.com/ipdk-io/ptf-tests/files/10485896/ptf_tests_run_lnt_all_release.log)
> 3. Fix for l3_dpdk_port_flapping_with_link_ports.py.  Unit test log [l3_dpdk_port_flap_with_link_log.txt](https://github.com/ipdk-io/ptf-tests/files/10486044/l3_dpdk_port_flap_with_link_log.txt)

Please update the pre_test as well, run the suite and share the log here.

**Review by dkaranjai — APPROVED** [review]
LGTM

**Pull request merged**
